on:
    workflow_dispatch:
jobs:
    hello_world_job:
      runs-on: ubuntu-latest
      name: Accessibility check 1
      steps:
        - name: Checkout code
          id: code-checkout
          uses: actions/checkout@v3
        - name: Stark check
          id: stark
          uses: abcdefghiraj/accessibility-check-action@main
          with:
            setup: 'npm i'
            serve: 'npm run dev'
            url: 'http://localhost:3000'
            token: 'test-token'
          env:
            STARK_REPORT_URL: 'http://localhost:3001'