on:
    workflow_dispatch:
  
  jobs:
    hello_world_job:
      runs-on: ubuntu-latest
      name: Accessibility check
      steps:
        - name: Checkout code
          id: code-checkout
          uses: actions/checkout@v3
        - name: Stark check
          id: stark
          uses: abcdefghiraj/puppeteer-action-test@main
          with:
            setup: 'npm i'
            serve: 'npm run dev'
            url: 'localhost:3000'